### ISSUE TITLE
Can't include otplib via import

### ISSUE THREAD

**Issue by osinakayah** [yeojz/otplib#159] opened 2019-04-06 12:54 UTC
1.import otplib from 'otplib'; console.log(otplib);//returns undefined
2.const otplib = require('otplib'); works fine

**Environment (please provide any relevant information):**
 - OS:  MacOSX
 - Node / Yarn: Yarn
 - Any frameworks: Express

**Comment by yeojz** [comment] 2019-04-07 06:14
@osinakayah can you try using:

```js
import * as otplib from 'otplib';

// or if you have a specific method
import { authenticator } from 'otplib'
```

**Comment by nshaikhinurov** [comment] 2019-04-29 07:48
> @osinakayah can you try using:
> 
> ```js
> import * as otplib from 'otplib';
> 
> // or if you have a specific method
> import { authenticator } from 'otplib'
> ```

That worked for me

**Comment by jojoob** [comment] 2019-05-23 11:35
Just had the same issue after updating. `import otplib from 'otplib` worked with version 10.0.1. This is a breaking change between 10.0.1 and 10.2.2.

**Comment by yeojz** [comment] 2019-05-24 03:11
Acknowledged. I was under the impression that it was a major change.

Will backport a fix over the weekend.

**Comment by yeojz** [comment] 2019-05-27 14:19
fix released with default export in v10.2.3

**Closed** 2019-08-25 14:22 UTC
Labels: bug, documentation, fix released

**Comment by RafaPolit** [comment] 2019-11-08 20:23
This error has somehow been ported to V11.0.1?

I am having the same issue but importing the "* as " works.

Thanks.

**Comment by yeojz** [comment] 2019-11-10 13:48
@RafaPolit It isn't an error. 
It was intended for v11 to shift to `import *` but was erroneously released as part of v10.

**Comment by RafaPolit** [comment] 2019-11-10 14:36
Thanks for the quick answer!

I guess then one final question: do I need to manually add Crypto if using the asterisk procedure as described by on the “individual libraries import” section?

At any rate, the v11 readme should then probably reflect this “import *“ change?

Thanks again for the library and the quick reply.

**Comment by yeojz** [comment] 2019-11-11 09:35
@RafaPolit crypto is part of the default exports.

instead of importing the whole library, you can just do 

```js
import { authenticator } from 'otplib';
```
